# Generated by Django 5.0.1 on 2024-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_pythonquizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonquizresult',
            name='quiz_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
